export const VentanaUtil = {
    INICIO : 1,
    SERVICIOS : 2,
    COTIZACIONES : 3,
    CHECKLISTS : 4,
    INVENTARIOS : 5,
    SEGMENTOS : 6,
    PROVEEDORES : 7,
    PLACAS : 8,
    CARDEX : 9,
    FINANZAS : 10,
    FACTURAS_DE_COMPRA : 11,
    RECURSOS_HUMANOS : 12,
    MODIFICACIONES : 13,
    USUARIOS_Y_PERMISOS : 14,
    SOPORTE : 15,
    REPORTES : 16,
    AUTORIZACIONES: 18
}